[package]
name = "rikulox-parse"
authors.workspace = true
edition.workspace = true
version.workspace = true
readme.workspace = true

[dependencies]
rikulox-ast = { version = "0.1.0", path = "../rikulox-ast" }
rikulox-scan = { version = "0.1.0", path = "../rikulox-scan" }
string-interner = "0.19.0"
