[package]
name = "rikulox-ast"
authors.workspace = true
edition.workspace = true
version.workspace = true
readme.workspace = true

[dependencies]
bijective-enum-map = "0.1.0"
string-interner = "0.19.0"
