name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-nextest

    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --all-targets --all-features
    - name: Test
      run: cargo nextest run --all-features --profile ci
    - name: Lint
      run: cargo clippy -- -D warnings
    - name: Format Check
      run: cargo fmt -- --check
