name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --all-targets --all-features
    - name: Test
      run: cargo test
    - name: Lint
      run: cargo clippy -- -D warnings
    - name: Format Check
      run: cargo fmt -- --check
